import React from 'react';
import { AnalysisReport } from '../types';
import ScoreGauge from './ScoreGauge';
import { Briefcase, Zap, TrendingUp, AlertCircle, MessageSquareQuote, Users, Tag, ArrowRightLeft, Search, CheckCircle2, Target, BarChart3, Puzzle, FileText } from 'lucide-react';

interface ReportViewProps {
  report: AnalysisReport;
  companyName: string;
}

const ReportView: React.FC<ReportViewProps> = ({ report, companyName }) => {
  return (
    <div className="space-y-6 animate-fade-in pb-10">
      
      {/* Header */}
      <div className="border-b border-slate-200 pb-4">
        <h2 className="text-2xl font-bold text-slate-900">Strategy Report: {companyName}</h2>
        <p className="text-slate-500 text-sm mt-1">Generated by Senior AI Consultant</p>
      </div>

      {/* Executive Summary */}
      <div className="bg-indigo-50/50 p-6 rounded-xl border border-indigo-100 shadow-sm">
        <div className="flex items-center space-x-2 mb-3">
          <FileText className="w-5 h-5 text-indigo-700" />
          <h3 className="text-lg font-bold text-indigo-900">Executive Summary</h3>
        </div>
        <p className="text-slate-800 text-sm leading-relaxed text-justify">
          {report.executiveSummary}
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column: Summary & Gaps */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* Business Intelligence */}
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
            <div className="flex items-center space-x-2 mb-4 border-b border-slate-100 pb-2">
              <Briefcase className="w-5 h-5 text-indigo-600" />
              <h3 className="text-lg font-semibold text-slate-800">Business Intelligence Summary</h3>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-y-4 gap-x-6">
              <div>
                <span className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-slate-400 mb-1">
                  <Search className="w-3 h-3" /> What They Do
                </span>
                <p className="text-slate-800 text-sm leading-relaxed">{report.businessIntelligence.whatTheyDo}</p>
              </div>

              <div>
                <span className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-slate-400 mb-1">
                  <Users className="w-3 h-3" /> Target Audience
                </span>
                <p className="text-slate-800 text-sm leading-relaxed">{report.businessIntelligence.targetAudience}</p>
              </div>

              <div>
                <span className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-slate-400 mb-1">
                  <ArrowRightLeft className="w-3 h-3" /> Sales Motion
                </span>
                <p className="text-slate-800 text-sm leading-relaxed">{report.businessIntelligence.salesMotion}</p>
              </div>

              <div>
                <span className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-slate-400 mb-1">
                  <Tag className="w-3 h-3" /> Likely Price Point
                </span>
                <p className="text-slate-800 text-sm leading-relaxed">{report.businessIntelligence.pricePoint}</p>
              </div>
            </div>

            {report.businessIntelligence.keyAssumptions.length > 0 && (
              <div className="mt-4 pt-4 border-t border-slate-50">
                <p className="text-xs text-slate-500 italic">
                  <span className="font-semibold text-slate-600">Assumptions:</span> {report.businessIntelligence.keyAssumptions.join(' • ')}
                </p>
              </div>
            )}
          </div>

          {/* Gap Analysis */}
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
            <div className="flex items-center space-x-2 mb-4 border-b border-slate-100 pb-2">
              <AlertCircle className="w-5 h-5 text-amber-500" />
              <h3 className="text-lg font-semibold text-slate-800">Digital Gap Analysis</h3>
            </div>
            <div className="space-y-4">
              {report.gapAnalysis.map((gap, idx) => (
                <div key={idx} className="flex items-start space-x-4 p-4 bg-slate-50 rounded-lg border border-slate-100 transition-colors hover:border-amber-200">
                  <span className="flex-shrink-0 w-8 h-8 bg-amber-100 text-amber-700 rounded-full flex items-center justify-center text-sm font-bold shadow-sm">
                    {idx + 1}
                  </span>
                  <div>
                    <h4 className="font-semibold text-slate-800 text-base mb-1">{gap.title}</h4>
                    <p className="text-slate-600 text-sm mb-2">{gap.description}</p>
                    <div className="flex items-start gap-1.5 text-amber-800 bg-amber-50/50 px-2 py-1.5 rounded text-xs font-medium border border-amber-100/50">
                       <span className="uppercase tracking-wider font-bold text-[10px] mt-0.5">Impact:</span>
                       <span>{gap.businessImpact}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Solutions Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
               Custom AI Solutions
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              
              {/* Solution A: Efficiency */}
              <div className="bg-gradient-to-br from-blue-50 to-white p-5 rounded-xl border border-blue-100 shadow-sm relative overflow-hidden group hover:border-blue-300 transition-colors">
                <div className="absolute top-0 right-0 p-3 opacity-10 group-hover:opacity-20 transition-opacity">
                  <Zap className="w-16 h-16 text-blue-600" />
                </div>
                <div className="relative z-10 flex flex-col h-full">
                  <div className="text-xs font-bold text-blue-600 uppercase tracking-wide mb-1 flex items-center gap-1">
                    <Zap className="w-3 h-3" /> Efficiency Focus
                  </div>
                  <h4 className="text-lg font-bold text-slate-900 mb-2 leading-tight">{report.solutionEfficiency.title}</h4>
                  <p className="text-slate-600 text-sm mb-4 flex-grow">{report.solutionEfficiency.description}</p>
                  
                  <div className="bg-blue-50/50 rounded-lg p-3 space-y-2 border border-blue-100/50 text-xs mt-auto">
                     <div className="flex items-center justify-between">
                        <span className="text-slate-500 flex items-center gap-1"><Target className="w-3 h-3"/> Funnel Stage</span>
                        <span className="font-semibold text-slate-700">{report.solutionEfficiency.funnelStage}</span>
                     </div>
                     <div className="flex items-center justify-between">
                        <span className="text-slate-500 flex items-center gap-1"><BarChart3 className="w-3 h-3"/> KPI</span>
                        <span className="font-semibold text-slate-700">{report.solutionEfficiency.kpi}</span>
                     </div>
                     <div className="flex items-center justify-between">
                        <span className="text-slate-500 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Exp. ROI</span>
                        <span className="font-bold text-blue-700">{report.solutionEfficiency.roi}</span>
                     </div>
                     <div className="pt-2 mt-2 border-t border-blue-100 text-slate-400 flex items-start gap-1">
                        <Puzzle className="w-3 h-3 mt-0.5 flex-shrink-0" />
                        <span className="italic leading-tight">{report.solutionEfficiency.integration}</span>
                     </div>
                  </div>
                </div>
              </div>

              {/* Solution B: Revenue */}
              <div className="bg-gradient-to-br from-emerald-50 to-white p-5 rounded-xl border border-emerald-100 shadow-sm relative overflow-hidden group hover:border-emerald-300 transition-colors">
                <div className="absolute top-0 right-0 p-3 opacity-10 group-hover:opacity-20 transition-opacity">
                  <TrendingUp className="w-16 h-16 text-emerald-600" />
                </div>
                <div className="relative z-10 flex flex-col h-full">
                  <div className="text-xs font-bold text-emerald-600 uppercase tracking-wide mb-1 flex items-center gap-1">
                    <TrendingUp className="w-3 h-3" /> Revenue Focus
                  </div>
                  <h4 className="text-lg font-bold text-slate-900 mb-2 leading-tight">{report.solutionRevenue.title}</h4>
                  <p className="text-slate-600 text-sm mb-4 flex-grow">{report.solutionRevenue.description}</p>
                  
                   <div className="bg-emerald-50/50 rounded-lg p-3 space-y-2 border border-emerald-100/50 text-xs mt-auto">
                     <div className="flex items-center justify-between">
                        <span className="text-slate-500 flex items-center gap-1"><Target className="w-3 h-3"/> Funnel Stage</span>
                        <span className="font-semibold text-slate-700">{report.solutionRevenue.funnelStage}</span>
                     </div>
                     <div className="flex items-center justify-between">
                        <span className="text-slate-500 flex items-center gap-1"><BarChart3 className="w-3 h-3"/> KPI</span>
                        <span className="font-semibold text-slate-700">{report.solutionRevenue.kpi}</span>
                     </div>
                     <div className="flex items-center justify-between">
                        <span className="text-slate-500 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> Exp. ROI</span>
                        <span className="font-bold text-emerald-700">{report.solutionRevenue.roi}</span>
                     </div>
                     <div className="pt-2 mt-2 border-t border-emerald-100 text-slate-400 flex items-start gap-1">
                        <Puzzle className="w-3 h-3 mt-0.5 flex-shrink-0" />
                        <span className="italic leading-tight">{report.solutionRevenue.integration}</span>
                     </div>
                  </div>
                </div>
              </div>

            </div>
          </div>

        </div>

        {/* Right Column: Score & Ice Breaker */}
        <div className="space-y-6">
          
          {/* Fit Score */}
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex flex-col items-center text-center">
            <h3 className="text-lg font-semibold text-slate-800 mb-4 w-full text-left">Automation Fit</h3>
            <ScoreGauge score={report.fitScore} />
            
             <div className={`mt-4 px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-wide ${
                report.dealPotential === 'High' ? 'bg-emerald-100 text-emerald-800 border border-emerald-200' :
                report.dealPotential === 'Medium' ? 'bg-amber-100 text-amber-800 border border-amber-200' :
                'bg-slate-100 text-slate-700 border border-slate-200'
            }`}>
                Deal Potential: {report.dealPotential}
            </div>

            <p className="mt-4 text-sm text-slate-500 italic">"{report.fitJustification}"</p>
          </div>

          {/* Ice Breaker */}
          <div className="bg-slate-900 text-white p-6 rounded-xl shadow-lg relative overflow-hidden">
            <div className="absolute -top-6 -left-6 w-24 h-24 bg-white opacity-10 rounded-full blur-2xl"></div>
            <div className="relative z-10">
              <div className="flex items-center space-x-2 mb-3">
                <MessageSquareQuote className="w-5 h-5 text-indigo-400" />
                <h3 className="text-lg font-semibold">Ice-Breaker Outreach</h3>
              </div>
              <div className="p-4 bg-white/10 rounded-lg backdrop-blur-sm border border-white/10">
                <p className="font-mono text-sm leading-relaxed text-slate-200">
                  {report.iceBreaker}
                </p>
              </div>
              <button 
                onClick={() => navigator.clipboard.writeText(report.iceBreaker)}
                className="mt-4 w-full py-2 bg-indigo-600 hover:bg-indigo-700 rounded-lg text-xs font-semibold uppercase tracking-wider transition-colors"
              >
                Copy to Clipboard
              </button>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default ReportView;